# Melbourne House Prices

This notebook is the final notebook of a first ML project on a local computer to practice the different algorithms, types of problems and get more practice at developing this type of projects. It is based on the data set for the [Melbourne House Pricing Kaggle competition](https://www.kaggle.com/c/home-data-for-ml-course)

The competition is really recommended for all the persosns that would like to start somewhere in ML.

## Basic Data Exploration

As mentioned in the post from [kaggle](https://www.kaggle.com/dansbecker/basic-data-exploration), the most important thing at the start of any project of this nature its to get familiar with the data.

In [32]:
## Other necessary for the notebook
from IPython.display import Image

import pandas as pd

# read the data set that is stored locally
house_melb_df = pd.read_csv('.csv')
print('data has {} rows and {} columns'.format(house_melb_df.shape[0],house_melb_df.shape[1]))
house_melb_df.head(10)

data has 1460 rows and 81 columns

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [28]:
house_melb_df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1459.000000,1459.000000,1232.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,...,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,2190.000000,57.378341,68.580357,9819.161069,6.078821,5.553804,1971.357779,1983.662783,100.709141,439.203704,...,472.768861,93.174777,48.313914,24.243317,1.794380,17.064428,1.744345,58.167923,6.104181,2007.769705
std,421.321334,42.746880,22.376841,4955.517327,1.436812,1.113740,30.390071,21.130467,177.625900,455.268042,...,217.048611,127.744882,68.883364,67.227765,20.207842,56.609763,30.491646,630.806978,2.722432,1.301740
min,1461.000000,20.000000,21.000000,1470.000000,1.000000,1.000000,1879.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,1825.500000,20.000000,58.000000,7391.000000,5.000000,5.000000,1953.000000,1963.000000,0.000000,0.000000,...,318.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000
50%,2190.000000,50.000000,67.000000,9399.000000,6.000000,5.000000,1973.000000,1992.000000,0.000000,350.500000,...,480.000000,0.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,2554.500000,70.000000,80.000000,11517.500000,7.000000,6.000000,2001.000000,2004.000000,164.000000,753.500000,...,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,2919.000000,190.000000,200.000000,56600.000000,10.000000,9.000000,2010.000000,2010.000000,1290.000000,4010.000000,...,1488.000000,1424.000000,742.000000,1012.000000,360.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000

## Interpret the data

From the previous cells, we can see that the data has **34857** rows and **21** columns. Clearly there are some variables that are described here that should not be describe as numerical variables. For example, the post code should not have an average value. The rest of the other values, can be interpreted as numerical values and so far, the summary above showcase a good description of the data. 

Some plots can also help in this part

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Machine Learning Model

Select the prediction variable. As for this case, it is the price of a house, this can be expressed in hundreds of thousands or even more. That is whhy, the first task is to change the prices to thousands.

In [4]:

y = house_melb_df.Price.fillna(house_melb_df.Price.median())
y.isna().any()

False

Select the 'features'. These are the columns that are input into the model. For this case, these are the columns that determine the price of a house.

In [5]:
#names of the columns of the features that are going to be used
features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

#Creating the subset of those columns 
X = house_melb_df[features]
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rooms       34857 non-null  int64
 1   Bathroom    26631 non-null  float64
 2   Landsize    23047 non-null  float64
 3   Lattitude   26881 non-null  float64
 4   Longtitude  26881 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 1.3 MB

As there are many values that are missing, it was decided to fill this ones with the median of the distribution (this is based on the fact that the median value is more stable against outliers)

In [6]:
# Go through the columns and fill in the missing values
for col in X.columns:
    # calculate the median of the column
    replacement = X[col].median()
    #replace the missing values 
    X[col] = X[col].fillna(value = replacement)

<ipython-input-6-7f4f5e6a34c9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].fillna(value = replacement)
<ipython-input-6-7f4f5e6a34c9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].fillna(value = replacement)
<ipython-input-6-7f4f5e6a34c9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].fillna(value = replacement)
<ipython-input-6-7f4f5e6a34c9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].fillna(value = replacement)
<ipython-input-6-7f4f5e6a34c9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].fillna(value = replacement)

In [7]:
# first few rows of the features
X.describe()

              Rooms      Bathroom       Landsize    Lattitude    Longtitude
count  34857.000000  34857.000000   34857.000000  34857.00000  34857.000000
mean       3.031012      1.713343     569.001520    -37.80994    145.003212
std        0.969933      0.652754    2763.907731      0.07929      0.105558
min        1.000000      0.000000       0.000000    -38.19043    144.423790
25%        2.000000      1.000000     357.000000    -37.84690    144.964400
50%        3.000000      2.000000     521.000000    -37.80760    145.007800
75%        4.000000      2.000000     598.000000    -37.77090    145.051750
max       16.000000     12.000000  433014.000000    -37.39020    145.526350

## Building the model

To build the model, we can use the vastly, and well documented library of [scikit-learn](sklearn.org) which contains bunch of methods, models, examples, tests, and in general tools, to make the building of a model super simple. To build a model;
1. **Define** what type of a model will it be? A decision tree? Some other type of model? Some other parameters of the model type are specified too.
2. **Fit** Capture patterns from the provided data. This is the heart of modeling.
3. **Predict** Predict the independent variable from the features.
4. **Evaluate**. Determine how accurate, precise, or the measure you are using, the model's predictions.

In [8]:
# Load the necessary libraries
from sklearn.tree import DecisionTreeRegressor

In [9]:
# Define model. Specify the number for random_state to ensure
# same results each run

house_model = DecisionTreeRegressor(random_state=1000)

# Fit the model 
house_model.fit(X,y)

DecisionTreeRegressor(random_state=1000)

Some machine learning models alllow some randomness in the model training and this might cause differences when these are run multiple times. Specifying a number for 'random_state' ensure you get the same results in each run. This is considered a **good practice** 
You can use any value, the model quality won't depend on exactly what value you choose.

Now, there is a fitted model that can be used to make predictions.

In practice, the idea is to use this model to predict the price of the new houses that are coming into the market rather than the houses that already have a price. 

For the sake of testing the fitted model, this is going to be tested in the first 5 observations of the data.|

In [10]:
print('Predictions for the next 5 houses')
houses = X.head()
print(houses)
print('The predictions are')
print(house_model.predict(houses))

Predictions for the next 5 houses
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
0      2       1.0     126.0   -37.8014    144.9958
1      2       1.0     202.0   -37.7996    144.9984
2      2       1.0     156.0   -37.8079    144.9934
3      3       2.0       0.0   -37.8114    145.0116
4      3       2.0     134.0   -37.8093    144.9944
The predictions are
[ 870000. 1480000. 1035000.  870000. 1465000.]

## Model Validation 
The idea of this part is to evaluate the performance of the model that was created above. In general, almost every model would be evaluated, the important part here is to define how is the model performance going to be measure. (Add reference)

There are many metrics that can be used for summarizing the model quality, a first example is the **Mean Absolute Error** or MAE. As its name describes it, the MAE is calculate by taking the average of the absolute value of the differencer between the prediction and the acutal value.

In [11]:
#import the metric
from sklearn.metrics import mean_absolute_error

#Create the predictions
predicted_prices = house_model.predict(X)
#Calculate the MAE
mean_absolute_error(y, predicted_prices)

66888.30484263679

What is the problem here? The meausre that was just calculated is an 'in-sample' measure. We use the same sample to build and to evaluate the model. This is not the best. This is a bad way to evaluate as the model was made to 'fit' this data. The model practical value comes from the predictions on new data, data that it has not seen before. This is called **validation/test data.**

Scikit-learn has a function that is called $\text{train_test_split}$

In [13]:
#import the train_test_split 
from sklearn.model_selection import train_test_split

# split the data into trainint and validation data. For both, features
# and targets. The split is based on a random number generator. 
# Supplying a numeric value
train_X, val_X, train_y, val_y = train_test_split(X,y, random_state = 0)

#Define the model 
house_model = DecisionTreeRegressor()

#Fit the model

house_model.fit(train_X, train_y)

## get the predicte prices on the test set
test_values = house_model.predict(val_X)

print(mean_absolute_error(val_y, test_values))

318717.3591299496

## Experimenting with different models.

Now that there is a way to measure the model and the estimations that it does, there is an important part in the job of a data scientist that is to try different methods to see which is the one that brings the best results. It is important that the methods used fit the problem that you are trying to solve. 

The [scikit-learn's documentation](http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html) contains relevant information that can help create the best possbile model. For example, the Decision Tree model that was created has many options. The most important options are the ones referring to the depth of the tree. (the depth of the tree is how many splits it makes before making a prediciton)

### Underfitting and overfitting.

As the depth increases, the number of splits that the tree divides the data is bigger and this leave every leaf with fewer observations. For example, depth = 2, will create four leaves, while depth = 10 will create 1024 leaves, with few observations on each of those.

That phenomenon is called **overfitting**. This is when the model matches the training data almost perfectly, but it does not do so with the test/validation data, but in case the tree is to shallow, it does not divide the data into distinct groups. This is the case when there are few divisions (imagine 4) and in each group would contain a big variety of houses. The predictions on the training and the test data will be far bad predictions. When this happens (perform bad also in the training data set) it is said that the model is **underfiting**

This can be seen when changing different parameters in the model. 
![title](over_under_fitting.png)

This can be tested with the model that was built before.

In [24]:
# Function to calculate different Mean average error.

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    '''
    Function to calculate the MAE from a specific model tree regressor
    with a max depth given by the log of the number of leaves.
    '''
    model  = DecisionTreeRegressor(max_leaf_nodes = max_leaf_nodes, random_state = 0)
    model.fit(train_X, train_y)
    
    pred_val = model.predict(val_X)
    
    mae = mean_absolute_error(val_y, pred_val)
    return mae

errors = []

leaf_sizes = [5,10,50,100,250,500,1000,5000,10000]

for leaf in leaf_sizes:
    partial_mae = get_mae(leaf, train_X, val_X, train_y, val_y)
    errors.append(partial_mae)
    print('Max leaves nodes: {} \t\t Mean Absolute Error: {}'.format(leaf, partial_mae))
    
best_leaf = leaf_sizes[errors.index(min(errors))]


print('And the best number of leaves that we can have is {} /n With a Mean Absolute Error of {}'.format(best_leaf, min(errors)))

Max leaves nodes: 5 		 Mean Absolute Error: 337991.6062293389
Max leaves nodes: 10 		 Mean Absolute Error: 322305.26694364886
Max leaves nodes: 50 		 Mean Absolute Error: 292951.50039843476
Max leaves nodes: 100 		 Mean Absolute Error: 290318.74399950984
Max leaves nodes: 250 		 Mean Absolute Error: 285592.1887993014
Max leaves nodes: 500 		 Mean Absolute Error: 283356.76612854964
Max leaves nodes: 1000 		 Mean Absolute Error: 289317.0210182337
Max leaves nodes: 5000 		 Mean Absolute Error: 310315.6496894938
Max leaves nodes: 10000 		 Mean Absolute Error: 318994.9424368698
And the best number of leaves that we can have is 500 /n With a Mean Absolute Error of 283356.76612854964

Now that the number of leaves and best tree size that are needed to obtain the best results, using all the data is possible as the results would be the most accurate. In this case, there is no need to keep the validation data as the decisions about the best model have been done.

In [21]:
#define the final model
final_model = DecisionTreeRegressor(max_leaf_nodes = best_leaf,random_state = 1)

# Predict 
final_model.fit(X, y)

# Made up example 
examples = []
new_house={'Rooms':3,
           'Bathroom':2.5, 
           'Landsize':185.4,
           'Lattitude':-35.8014,
           'Longtitude':146.9958}
examples.append(new_house)
examples = pd.DataFrame(examples)
examples
final_model.predict(examples)

array([669770.96138996])

## Using more sophisticated Algorithms

**RANDOM FORESTS**

The decision trees used before leave a dificult decision. A deep tree with many leaves will overfit the data as each prediction is coming from historical data from only a few houses in that leaf. On the other hand, a shallow tree with few leaves will perform poorly because it will fail to capture as many distinctions in the raw data. 

All the sophisticated current modelling techniques have this tension between underfitting and overfitting, but there are models that have clever ideas that can lead to a better performance. The best example is the **random forest**.

Random forest uses many trees, and it makes its prediction by averaging the predictions of each component tree (each tree in the forest). It generally has a better predictve accuracy than a single decision tree and it works well with default parameters. With more modelling practice, it is possible to find other models with better performance, but many of those are sensitive to getting the right parameters. 

Building a _random forest_ is similar to how the decision tree was built. The difference is that now `RandomForestRegressor` class is used instead of `DecisionTreeRegressor`

In [25]:
# Import the necessary packages
from sklearn.ensemble import RandomForestRegressor

# Create the RandomForestRegressor object
forest_model = RandomForestRegressor(random_state = 1)

#fit the model
forest_model.fit(train_X, train_y)

#Make the predictions
predictions = forest_model.predict(val_X)

#Calculate the Mean Absolute Error

mae = mean_absolute_error(val_y, predictions)

print('With the Random Forest Regressor, a MAE of {} was achieved'.format(mae))

With the Random Forest Regressor, a MAE of 263568.53601435584 was achieved

In [26]:
# Comparison of the results 
mae - min(errors)

-19788.230114193808

There is a reduction on the mean absolute error. It is about 20.000 in Australian Dollars that is the currency of the houses in the data set. There are still parameters that can be change will creating the Random Forest object similar to the one used on the Decision Tree. But one of the best features of Random Forest is that they generally work reasonably weel even without that tuning.